services:
  dj:
    build: .
    container_name: django
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    volumes:
      - todo_db_data:/var/lib/postgresql/data/

volumes:
  todo_db_data: null